"""Update user organization relationship

Revision ID: 1cfbbb02d983
Revises: 92603c3c170c
Create Date: 2025-05-14 20:59:18.834650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cfbbb02d983'
down_revision = '92603c3c170c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('VOLUNTEER', 'ORGANIZATION', 'ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('VOLUNTEER', 'ORGANIZATION', 'ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
