"""Initial migration

Revision ID: 250161ca1d8f
Revises: 
Create Date: 2025-05-24 23:01:29.492913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '250161ca1d8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_table('system_logs')
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'verified')
    op.drop_column('organizations', 'phone')
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='system_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    # ### end Alembic commands ###
