"""Add profile fields to users table2

Revision ID: 3f68fb6762da
Revises: 6a0c7b0da9ca
Create Date: 2025-05-27 22:38:43.414492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f68fb6762da'
down_revision = '6a0c7b0da9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
