"""Create volunteers table

Revision ID: 7c7be9df6562
Revises: 3f68fb6762da
Create Date: 2025-05-27 22:44:52.813760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c7be9df6562'
down_revision = '3f68fb6762da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_volunteers_id', table_name='volunteers')
    op.drop_table('volunteers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='volunteers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='volunteers_pkey'),
    sa.UniqueConstraint('user_id', name='volunteers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_volunteers_id', 'volunteers', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='system_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    # ### end Alembic commands ###
