"""Add organization_id to User model

Revision ID: 92603c3c170c
Revises: d97ee8e93ec3
Create Date: 2025-05-13 21:40:23.931137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92603c3c170c'
down_revision = 'd97ee8e93ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
