"""Add bidirectional relationship between User and Admin

Revision ID: a49bd6b09b15
Revises: 1cfbbb02d983
Create Date: 2025-05-16 22:52:08.663614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a49bd6b09b15'
down_revision = '1cfbbb02d983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='system_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    # ### end Alembic commands ###
